CREATE DATABASE IF NOT EXISTS burgers;

USE burgers;

CREATE TABLE burgers (
    id INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(255) NOT NULL,
    devoured BOOL DEFAULT FALSE,
    PRIMARY KEY (id)
);